### ISSUE TITLE
Accuracy near branch point

### ISSUE THREAD

**Issue by danaj** [DarkoVeberic/LambertW#2]
When testing, some of the values for the primary branch near the branch point are less accurate than desired, so the test_accuracy program is slightly misleading.

LambertW(-0.36787944117114235176)  ~  -0.999998722970745209730771987

Fukushima::LambertW(0, x) and utl::LambertW(0,x) both return -0.99999872292669178542  on x86_64/gcc 4.4.7, which has an error of 4.4e-11.

[Note:  thank you very much for publishing results at arXiv and for making open source software]

**Comment by DarkoVeberic** [comment]
Dear danaj,
I am deeply sorry for not replying sooner, it required holidays to get some free time...
I am afraid all the implementations I've seen have exactly the same problem. We all use the inverse series of the branch-point expansion. I think I understand why this happens, the function becomes **really** steep nearing the (non-zero!) branch point so that the effective square-root behavior is eating away accurate decimal places. I will give it a try to find something better, but let me just use your numbers x=-0.36787944117114235176 and y=-0.999998722970745209730771987 above and state that since the Lambert W is a solution to the x = y e^y function, for the latter I get
y e^y = -0.367879441171142351760000000
which is exactly equal to your x.

**Comment by DarkoVeberic** [comment]
Dear @danaj,
After several days of braking my head with this issue, all I can tell for sure is that this behavior is observed in all implementations which use the series around the branch point (-1/e, -1). You can see it in the original Fukushima's implementation in Fortran, as well as in Briggs' GNU Scientific Library gsl_sf_lambert. I tried to replace the inverse series of x*e^x with the different Corless' inverse series of the tree function, but unfortunately I get exactly the same for W(-1/e+d) the accuracy goes from 16 decimal places at d=10^-3 down to 9 decimal places for d=10^-15.

**Comment by DarkoVeberic** [comment]
Btw, @danaj thanks for making such tests!

**Comment by DarkoVeberic** [comment]
The only sure thing is that W(x) e^W(x) is even close to the branch point equal to x to at least 16 decimal places, which (maybe?) is the only thing that matters...

**Comment by DarkoVeberic** [comment]
@danaj 
Try this in Mathematica:
`Sort[Table[With[{d = 10^RandomReal[{-16, -0.5}]}, With[{x = -1/E + d}, {d, -Log[10, Abs[LambertW[0, x] - LambertW[0, SetPrecision[x, 20]]]]}]], {20}]]`
The Mathematica function itself has this problem and this explains why no matter which implementation I took, the accuracy close to -1/E always looked the same...

**Comment by DarkoVeberic** [comment]
Since all existing implementations are using the same inverse branch-point expansion and it is not clear how Mathematica is obtaining the values in this range, I am closing this issue. In case you have more insights, please, do not hesitate and reopen it.
